config/routes.rb
Project::Application.routes.draw do

  match '/home' => 'home#index'

  match '/select_markets' => 'farmers_markets#select_market'

  match '/select_product' => 'home#shop'

  get '/categories/:id/get_categories' => 'categories#get_categories'

  get '/categories/:id/get_products' => 'categories#get_products'

  post '/carts/add_to_cart' => 'carts#add_to_cart'

  get '/carts/checkout' => 'carts#checkout'

  resources :products do
    collection do
      get 'get_all_products'
    end

    collection do
      get 'get_products'
    end
  end

  resources :categories do
    collection do
      get 'get_all_categories'
    end
  end

  devise_for :users

  resources :carts do
    collection do
      get 'add_to_cart'
    end
  end

  resources :farmers_markets do
    collection do
      get 'get_nearby_markets'
    end

    collection do
      get 'set_market'
    end
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :FarmersMarket
  has_many :Product
  attr_accessible :FarmersMarket_id, :Product_id, :quantity, :user_id
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_filter :set_cart, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @carts = Cart.all
    respond_with(@carts)
  end

  def show
    respond_with(@cart)
  end

  def new
    @cart = Cart.new
    respond_with(@cart)
  end

  def edit
  end

  def checkout
    user_id = session["warden.user.user.key"][0][0]
    checkout_data = Cart.where("\"user_id\" = ?", user_id)
    print @checkout_data
    print "PRINTING ITEMS FROM CART"
    @products = []
    @amount = 0
    checkout_data.each do |item|
      @products.insert(-1, [Product.find(item.Product_id).name, FarmersMarket.find(item.FarmersMarket_id).name, item.quantity, Product.find(item.Product_id).price])
      @amount = @amount + Product.find(item.Product_id).price*item.quantity
    end
    Cart.destroy_all(user_id: user_id)
    print @products
    print "AMOUNT IS"
    print @amount
    respond_to do |format|
      format.html { render :template => "carts/checkout" }
    end
  end

  def add_to_cart
    p session["market_id"]
    market_id = session["market_id"]
    p session["warden.user.user.key"][0][0]
    user_id = session["warden.user.user.key"][0][0]
    product_id = params[:product_id]
    quantity = params[:quantity]

    cart = Cart.new(:user_id => user_id, :Product_id => product_id, :FarmersMarket_id => market_id, :quantity => quantity)
    cart.save

    respond_to do |format|
      msg = Hash.new
      format.json {render :json => msg}
    end
  end

  def create
    @cart = Cart.new(params[:cart])
    @cart.save
    respond_with(@cart)
  end

  def update
    @cart.update_attributes(params[:cart])
    respond_with(@cart)
  end

  def destroy
    @cart.destroy
    respond_with(@cart)
  end

  private
    def set_cart
      @cart = Cart.find(params[:id])
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= collection_select :cart, :user_id, User.all, :id, :email %>
  </div>
  <div class="field">
    <%= f.label :Category %><br />
    <%= collection_select :cart, :Product_id, Product.all, :id, :name %>
  </div>
   <div class="field">
    <%= f.label :FarmersMarket %><br />
    <%= collection_select :cart, :FarmersMarket_id, FarmersMarket.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/checkout.html.erb
<h2>Your orders have been placed</h2>

<table border="true">
  <tr>
    <th>Product</th>
    <th>Farmersmarket</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>

<% @products.each do |item| %>
  <tr>
    <td><%= item[0] %></td>
    <td><%= item[1] %></td>
    <td><%= item[2] %></td>
    <td><%= item[3] %></td>
  </tr>
<% end %>
</table>

<h4> Your total bill amount is <%=@amount %> </h4>

<br />

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th>User</th>
    <th>Product</th>
    <th>Farmersmarket</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.user %></td>
    <td><%= cart.Product_id %></td>
    <td><%= cart.FarmersMarket_id %></td>
    <td><%= cart.quantity %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @cart.user %>
</p>

<p>
  <b>Product:</b>
  <%= @cart.Product_id %>
</p>

<p>
  <b>Farmersmarket:</b>
  <%= @cart.FarmersMarket_id %>
</p>

<p>
  <b>Quantity:</b>
  <%= @cart.quantity %>
</p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>