config/routes.rb
Project::Application.routes.draw do

  match '/home' => 'home#index'

  match '/select_markets' => 'farmers_markets#select_market'

  match '/select_product' => 'home#shop'

  get '/categories/:id/get_categories' => 'categories#get_categories'

  get '/categories/:id/get_products' => 'categories#get_products'

  post '/carts/add_to_cart' => 'carts#add_to_cart'

  get '/carts/checkout' => 'carts#checkout'

  resources :products do
    collection do
      get 'get_all_products'
    end

    collection do
      get 'get_products'
    end
  end

  resources :categories do
    collection do
      get 'get_all_categories'
    end
  end

  devise_for :users

  resources :carts do
    collection do
      get 'add_to_cart'
    end
  end

  resources :farmers_markets do
    collection do
      get 'get_nearby_markets'
    end

    collection do
      get 'set_market'
    end
  end
end

app/models/farmers_market.rb
class FarmersMarket < ActiveRecord::Base

  has_many :Products
  attr_accessible :city, :county, :facebook, :name, :state, :street, :website, :zip
  validates :city,presence: true
  validates :state,presence: true
  validates :street,presence: true
  validates :name,presence: true
end

app/controllers/farmers_markets_controller.rb
class FarmersMarketsController < ApplicationController
  before_filter :set_farmers_market, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @farmers_markets = FarmersMarket.all
    respond_with(@farmers_markets)
  end

  def show
    respond_with(@farmers_market)
  end

  def new
    @farmers_market = FarmersMarket.new
    respond_with(@farmers_market)
  end

  def edit
  end

  def create
    @farmers_market = FarmersMarket.new(params[:farmers_market])
    @farmers_market.save
    respond_with(@farmers_market)
  end

  def update
    @farmers_market.update_attributes(params[:farmers_market])
    respond_with(@farmers_market)
  end

  def destroy
    @farmers_market.destroy
    respond_with(@farmers_market)
  end



=begin
  def get_nearby_markets
    response_hashlist = Hash.new
    @nearby_markets = FarmersMarket.where("city = ?", params[:city])
    
    i = 0
    @nearby_markets.each do |market|
      response_hashlist[i] = market.as_json
      i = i + 1
    end

    puts response_hashlist

    puts response_hashlist.to_json
    #respond_with(response_hashlist)

    respond_to do |format|
      #msg = {:name => "ameya", :city => "philly"}
      msg = response_hashlist
      format.json {render :json => msg}
    end
  end
=end

  def get_nearby_markets
    @farmers_markets = FarmersMarket.where("city = ?", params[:city])
    respond_to do |format|
      format.html {render :template => "farmers_markets/nearby_markets"}
    end
  end
  
  private
    def set_farmers_market
      @farmers_market = FarmersMarket.find(params[:id])
    end
end

app/helpers/farmers_markets_helper.rb
module FarmersMarketsHelper
end

app/views/farmers_markets/_form.html.erb
<%= form_for(@farmers_market) do |f| %>
  <% if @farmers_market.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@farmers_market.errors.count, "error") %> prohibited this farmers_market from being saved:</h2>

      <ul>
      <% @farmers_market.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :county %><br />
    <%= f.text_field :county %>
  </div>
  <div class="field">
    <%= f.label :facebook %><br />
    <%= f.text_field :facebook %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/farmers_markets/edit.html.erb
<h1>Editing farmers_market</h1>

<%= render 'form' %>

<%= link_to 'Show', @farmers_market %> |
<%= link_to 'Back', farmers_markets_path %>

app/views/farmers_markets/get_nearby_markets.html.erb
	<script>
		function get_farmers_markets()
		{
			var selected_city = new Object();
			e = document.getElementById("city_name");
			selected_city["city"] = e.options[e.selectedIndex].value;
			//alert(selected_city["city"]);

			$.ajax({
	        	type: "GET",
	        	url: "/farmers_markets/get_farmers_markets",
	        	data: selected_city,
	        	dataType: "json"
      		})

      		.done(function(data){
      			

      		})


		}
	</script>


	
		<select name="city" id="city_name">
			<option value="New York">New York</option>
			<option value="Philadelphia">Philadelphia</option>
		</select>
		<input type="text" id="market_name">
		<button onclick="get_farmers_markets()">Get Markets</button>
	

app/views/farmers_markets/index.html.erb
<h1>Listing farmers_markets</h1>

<table>
  <tr>
    <th>City</th>
    <th>County</th>
    <th>Facebook</th>
    <th>Name</th>
    <th>State</th>
    <th>Street</th>
    <th>Website</th>
    <th>Zip</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @farmers_markets.each do |farmers_market| %>
  <tr>
    <td><%= farmers_market.city %></td>
    <td><%= farmers_market.county %></td>
    <td><%= farmers_market.facebook %></td>
    <td><%= farmers_market.name %></td>
    <td><%= farmers_market.state %></td>
    <td><%= farmers_market.street %></td>
    <td><%= farmers_market.website %></td>
    <td><%= farmers_market.zip %></td>
    <td><%= link_to 'Show', farmers_market %></td>
    <td><%= link_to 'Edit', edit_farmers_market_path(farmers_market) %></td>
    <td><%= link_to 'Destroy', farmers_market, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Farmers market', new_farmers_market_path %>

app/views/farmers_markets/nearby_markets.html.erb
<h1 align="center">Select a farmer's market</h1>

<table border='true'>
  <tr>
  	<th>Name</th>
    <th>City</th>
    <th>County</th>
    <th>Facebook</th>
    <th>State</th>
    <th>Street</th>
    <th>Website</th>
    <th>Zip</th>
    <th>Link</th>
  </tr>

<% @farmers_markets.each do |farmers_market| %>
  <tr>
  	<td><%= farmers_market.name %></td>
    <td><%= farmers_market.city %></td>
    <td><%= farmers_market.county %></td>
    <td><%= farmers_market.facebook %></td>
    <td><%= farmers_market.state %></td>
    <td><%= farmers_market.street %></td>
    <td><%= farmers_market.website %></td>
    <td><%= farmers_market.zip %></td>
    <!--td><%= link_to 'Visit', farmers_market %></td-->
    <td><a href="/categories/<%= farmers_market.id %>/get_categories">Click here to visit</a></td>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Farmers market', new_farmers_market_path %>

app/views/farmers_markets/new.html.erb
<h1>New farmers_market</h1>

<%= render 'form' %>

<%= link_to 'Back', farmers_markets_path %>

app/views/farmers_markets/select_market.html.erb
	<script>
		function get_farmers_markets()
		{
			var selected_city = new Object();
			e = document.getElementById("city_name");
			selected_city["city"] = e.options[e.selectedIndex].value;
			alert(selected_city["city"]);

			$.ajax({
	        	type: "GET",
	        	url: "/farmers_markets/get_nearby_markets",
	        	data: selected_city,
	        	dataType: "json"
      		})

      		.done(function(data){
      			//var str = JSON.stringify(data, null, 2); 
      			alert(data[0]["name"]);

      		})
		}
	</script>


	
		<select name="city" id="city_name">
			<option value="New York City">New York City</option>
			<option value="Philadelphia">Philadelphia</option>
		</select>
		<input type="text" id="market_name">
	<button onclick="get_farmers_markets()">Get Markets</button>

	<a href="/farmers_markets/set_market?market_id=1">Display Market</a>
	

app/views/farmers_markets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>City:</b>
  <%= @farmers_market.city %>
</p>

<p>
  <b>County:</b>
  <%= @farmers_market.county %>
</p>

<p>
  <b>Facebook:</b>
  <%= @farmers_market.facebook %>
</p>

<p>
  <b>Name:</b>
  <%= @farmers_market.name %>
</p>

<p>
  <b>State:</b>
  <%= @farmers_market.state %>
</p>

<p>
  <b>Street:</b>
  <%= @farmers_market.street %>
</p>

<p>
  <b>Website:</b>
  <%= @farmers_market.website %>
</p>

<p>
  <b>Zip:</b>
  <%= @farmers_market.zip %>
</p>


<%= link_to 'Edit', edit_farmers_market_path(@farmers_market) %> |
<%= link_to 'Back', farmers_markets_path %>